### ISSUE TITLE
Add OSXArm & ppc64le builds

### ISSUE THREAD

**Issue by ghost** [conda-forge/pyzstd-feedstock#5]
@conda-forge/help-ppc64le
@conda-forge/help-osx-arm64

Could you add OSXArm & ppc64le builds?

Please throw me a link of doc if it can be done by myself.

**Comment by xhochy** [comment]
Pleas add this feedstock to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt and https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt

Then the bot will make appropriate PRs.

**Comment by ghost** [comment]
Thanks.
